repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: \.svg$
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-json
        exclude: tsconfig.*\.json$
      - id: check-yaml
      - id: mixed-line-ending

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.0
    hooks:
      - id: ruff-format
        files: ^backend/
      - id: ruff
        args: [--fix]
        files: ^backend/
